name: spendzz
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_easyloading:
  fluttertoast:
  form_field_validator:
  carousel_slider: ^4.0.0
  page_transition:
  flutter_rating_bar:
  page_indicator:
  flutter_switch:
  material_segmented_control: ^3.1.2
  image_cropper:
  shared_preferences:
  flutter_html:
  http:
  timer_button:
  confetti: ^0.6.0
  flutter_countdown_timer:
  group_radio_button:
  loading_gifs:
  loading_indicator:
  flutter_spinkit:
  email_validator:
  image_picker:
  progress_dialog_null_safe:
  mime:
  geolocator:
  geocoding:
  razorpay_flutter:
  image_crop:
  cached_network_image:
  camera: ^0.9.4+4
  url_launcher:
  share: ^2.0.4
  open_file: ^3.2.1
  webview_flutter: ^3.0.0
  invoiceninja: ^0.0.9
  file_support: ^1.0.3+6
  get:
  flutter_pin_code_fields: ^1.1.0
  shimmer: ^2.0.0
  qr_code_scanner:
  flutter_contacts:
  connectivity_plus: ^1.0.6
  data_connection_checker:
  internet_connection_checker:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Regular.ttf

